### ISSUE TITLE
Question about basics of BTS7002 shield

### ISSUE THREAD

**Issue by ZivojinM** [BrixInMotion/efuse-spotwelder#2]
Hey! Just saw your comment on Hackster efuse project, as I was looking around online for clarification on how to properly use the BTS7002-1EPP shield that I just bought. I want to use it in my vehicle to control a pair of LED bulbs. As a beginner, I have a few problems understanding the correct setup - so perhaps you could help?

In the vehicle, I plan to power Arduino thru the 5V pin (voltage coming from a DC converter). Using 12V on the main Vbat terminal of the BTS shield, I presume Arduino is protected from those voltages? The shield has a GND terminal as well, which I presume should go to the chassis ground, but what about Arduino GND?

I'm using 3 buttons on those 2 LEDs with EZbutton library for debouncing, it does work on my test bench but I'm not sure if it's all "by the books". In the updated BTS info page I saw mention of using Infineon library on the Arduino sketch for BTS shield. I took seemingly old button-test code from Infineon Profet2 git page and chopped it for my case, you can take a look at it here - https://pastebin.com/7hW4wF0t

And a rough schematic of what I'm doing - https://i.imgur.com/csCOwoN.jpg

Sorry for the long question, thanks for any help :)

**Comment by BrixInMotion** [comment]
Hi,

seems like a cool project to start!
In this case, Arduino GND and shield-GND are the same and both go to chassis GND. I'm also pretty sure that input- and output-ground on your DC converter are directly connected. Your schematics looks ok so far.

So I guess you already saw the new Infineon docu for the shield: https://high-side-switch.readthedocs.io/en/latest/sw-frmwk/arduino/arduino-getting-started.html#arduino-getting-started

Best Regards

**Comment by ZivojinM** [comment]
Saw that page just earlier today, this is where I first seen the BTS700x-button-test.ino example where the #include <hss-shield-bts700x-ino.hpp> was in the header - I don't recall seeing that in the button test example I found on Infineon git back when I bought the shield. I presume I need to rework my code :D 

Also if I can ask, on that page there's a pinout diagram of the shield - when I'm using buttons to switch the loads on the shield, am I allowed to use any GPIO or just D9 / D10 / D10 / D3 (IN1 to IN4) ?

And final - do you know of a forum of sorts, discord, slack or anything similar where people good with embedded tech hang out and take on gigs? I really love tinkering with this but it's just too overwhelming, would like to have someone help me out when I get stuck. Thanks for your time for real!

**Comment by BrixInMotion** [comment]
If you only want to switch the high-side-switches on and off you don't need the library, it's totally ok to keep it like in your code. The library using the #include is more helpfull if you also want to read the current and get the diagnosis status of the BTS7002. 

Second question I'm not sure what you mean. If you want to read the button with the Arduino, you should connect it to either a free GPIO or use one of the LED pins as an input. If you want directly to switch the HSS with the button without Arduino, you need the correct In[1-4] of course. 

Sorry I don't know any specific forum, but I'm pretty sure you'll find something on the internet or just meet other people.

BR
